server:
  address: localhost
  port: 8002

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20 #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 60 #租期到期时间（默认90秒）
    instance-id: ${server.address}:${server.port}
    ip-address: ${server.address}    # 使用docker部署时 指定此实例的ip
    prefer-ip-address: true    # 注册时使用ip而不是主机名
  client:
    healthcheck:
      enabled: true #开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://${server.address}:1111/eureka/
quartz:
  enabled: true
spring:                                      #Quartz调度中心
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
  thymeleaf:
    mode: HTML5
    cache: false
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    encoding: UTF-8
    suffix: .html
    check-template-location: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
